name: Test

on: 
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - name: check out
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: build
        run: go build ./...

      - name: test
        run: go test ./... -v
